springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: 사용자
      paths-to-match:
        - /v1/member/**
        - /v1/board/**
    - group: 관리자
      paths-to-match:
        - /v1/admin/**